export const GET_DOGS = "GET_DOGS",
	GET_TEMPERAMENTS = "GET_TEMPERAMENTS",
	FILTER_BY_CREATED = "FILTER_BY_CREATED",
	FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT",
	SORT = "SORT",
	GET_BY_NAME = "GET_BY_NAME",
	GET_DETAIL = "GET_DETAIL",
	CLEAR_DETAIL = "CLEAR_DETAIL";
